# Generated by Django 5.1.5 on 2025-04-04 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_caseupdate_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='core.machine'),
        ),
    ]
